# Generated by Django 6.0.5 on 2026-05-25 06:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('state_tax_region', models.CharField(max_length=100)),
                ('pan', models.CharField(max_length=10)),
                ('tax_regime', models.CharField(default='NEW_REGIME', max_length=20)),
                ('base_salary_structure_dict', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemRuleConfigurationORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('json_rules_matrix', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PayrollLedgerORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period', models.CharField(max_length=7)),
                ('gross_total', models.FloatField()),
                ('net_payout', models.FloatField()),
                ('breakdown_log', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_engine.employeeorm')),
            ],
        ),
    ]
