# Generated by Django 6.0.5 on 2026-05-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payrollledgerorm',
            constraint=models.UniqueConstraint(fields=('employee', 'pay_period'), name='unique_employee_payroll_per_period'),
        ),
    ]
