# Generated by Django 6.0.5 on 2026-05-25 11:38

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_engine', '0002_payrollledgerorm_unique_employee_payroll_per_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Maharashtra Corporate Template', max_length=150)),
                ('state_code', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicSalaryComponentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_code', models.CharField(help_text='e.g., PF, PT, HRA, BASIC', max_length=50)),
                ('name', models.CharField(help_text='e.g., Provident Fund Deduction Rule', max_length=150)),
                ('sequence', models.PositiveIntegerField(help_text='Processing priority order index.')),
                ('configuration_schema', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Houses nested computational schema specifications variables.')),
                ('is_active', models.BooleanField(default=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='payroll_engine.salarystructure')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('structure', 'component_code')},
            },
        ),
    ]
