# Generated by Django 6.0.5 on 2026-05-26 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_engine', '0003_salarystructure_dynamicsalarycomponentrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., BASIC, HRA, PF, PT', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('BASE', 'Base Salary'), ('ALLOWANCE', 'Allowance'), ('DEDUCTION', 'Deduction')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientPayrollRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(help_text='ID of the client company/tenant')),
                ('calculation_type', models.CharField(choices=[('FLAT', 'Fixed Amount'), ('PERCENTAGE', 'Percentage Based'), ('SLAB_RANGE', 'Slab/Range Based'), ('CONDITION_BASED', 'Conditional Threshold')], max_length=20)),
                ('rule_config', models.JSONField(help_text='Dynamic configuration object tailored to calculation_type')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll_engine.salarycomponent', to_field='code')),
            ],
            options={
                'db_table': 'client_payroll_rules',
                'ordering': ['-effective_from'],
            },
        ),
    ]
